import { Accommodation } from './types';

export const ACCOMMODATIONS: Accommodation[] = [
  {
    id: '1',
    name: 'Heritage Ahungalla',
    type: 'Villa',
    location: 'Ahungalla',
    description: 'A legendary 5-star resort designed by Geoffrey Bawa, offering ultimate barefoot luxury in a tropical paradise.',
    price: 320,
    rating: 4.9,
    imageUrl: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?q=80&w=2070&auto=format&fit=crop',
    amenities: ['Geoffrey Bawa Design', 'Private Beach', 'Infinity Pools', 'Fine Dining'],
    maxGuests: 4,
  },
  {
    id: '2',
    name: 'Blaze Bolgoda',
    type: 'Villa',
    location: 'Bolgoda',
    description: 'A serene luxury boutique villa set on the banks of the Bolgoda Lake, perfect for a private getaway.',
    price: 250,
    rating: 4.8,
    imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=2070&auto=format&fit=crop',
    amenities: ['Lake View', 'Private Pool', 'Kayaking', 'Organic Garden'],
    maxGuests: 6,
  },
  {
    id: '3',
    name: 'Hikka Hikkaduwa',
    type: 'Room',
    location: 'Hikkaduwa',
    description: 'Vibrant and modern accommodation in the heart of Hikkaduwa, offering easy access to the reef and surf.',
    price: 180,
    rating: 4.7,
    imageUrl: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?q=80&w=2070&auto=format&fit=crop',
    amenities: ['Near Reef', 'Surf Access', 'Rooftop Bar', 'Eco-friendly'],
    maxGuests: 2,
  },
  {
    id: '4',
    name: 'Heritage Luxury Villa',
    type: 'Villa',
    location: 'Ahungalla',
    description: 'An extension of the Heritage brand, offering private villa experiences with dedicated butler service.',
    price: 550,
    rating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2071&auto=format&fit=crop',
    amenities: ['Butler Service', 'Private Chef', 'Poolside Lounge', 'Library'],
    maxGuests: 8,
  },
  {
    id: '5',
    name: 'Blaze Lakefront Suite',
    type: 'Suite',
    location: 'Bolgoda',
    description: 'Indulge in the tranquility of the lake with our premium suites featuring panoramic water views.',
    price: 200,
    rating: 4.6,
    imageUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?q=80&w=2080&auto=format&fit=crop',
    amenities: ['Balcony', 'Lake View', 'Jacuzzi', 'Breakfast Included'],
    maxGuests: 3,
  },
  {
    id: '6',
    name: 'Hikka Beachfront Room',
    type: 'Room',
    location: 'Hikkaduwa',
    description: 'Wake up to the sound of the ocean in our minimalist beachfront rooms designed for comfort and relaxation.',
    price: 150,
    rating: 4.5,
    imageUrl: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=2070&auto=format&fit=crop',
    amenities: ['Ocean View', 'Hammock', 'Rain Shower', 'Local Art'],
    maxGuests: 2,
  },
];
